### ISSUE TITLE
Gilbert Renton - Hotel Ton

### ISSUE THREAD

**Issue by WarezzK** [WarezzK/DeusEx-CzechAnniversaryMod#1]
Chybne znaky v dialogu.

**Comment by mr-flibble** [comment]
Potvrzuji :-)
![deusex 2016-09-18 19-39-12-63](https://cloud.githubusercontent.com/assets/5197625/18617761/a90db984-7dd7-11e6-96f8-a7acba570247.jpg)

**Comment by WarezzK** [comment]
Aktualizace kompletního dialogu - nyní bude fungovat i s diakritikou.
