### ISSUE TITLE
Juan Lebedev - 747

### ISSUE THREAD

**Issue by mr-flibble** [WarezzK/DeusEx-CzechAnniversaryMod#8]
Chybne znaky v dialogu.
![deusex 2016-09-18 21-46-34-21](https://cloud.githubusercontent.com/assets/5197625/18618554/7674e4ae-7de9-11e6-8bbe-66854060cc85.jpg)

**Comment by WarezzK** [comment]
Aktualizace kompletního dialogu - nyní bude fungovat i s diakritikou.
