### ISSUE TITLE
Red Arow Member, Max Chen, Chen's Bodyguard - Lucky Money

### ISSUE THREAD

**Issue by mr-flibble** [WarezzK/DeusEx-CzechAnniversaryMod#9]
Chybne české znaky - jak v dialogu, tak v textové bublině
Vypadá to že u všech členů red arrow 

![deusex 2016-09-18 21-56-02-50](https://cloud.githubusercontent.com/assets/5197625/18618616/d3dd69bc-7dea-11e6-9944-e2e26c2e2fbd.jpg)
![deusex 2016-09-18 21-57-26-21](https://cloud.githubusercontent.com/assets/5197625/18618621/ee626030-7dea-11e6-917d-bec0d03c0b5a.jpg)
![deusex 2016-09-18 21-57-58-99](https://cloud.githubusercontent.com/assets/5197625/18618636/1dba08d8-7deb-11e6-99ad-908a11156a87.jpg)

**Comment by WarezzK** [comment]
Aktualizace kompletního souboru - nyní bude vše fungovat i s diakritikou.

**Comment by mr-flibble** [comment]
Potvrzuji že je vyřešené :-)
![deusex 2016-09-19 21-06-55-03](https://cloud.githubusercontent.com/assets/5197625/18645333/11210500-7ead-11e6-99c9-a1a03bfecb8c.jpg)
